[tools]
ruby = "4.0"
node = "latest"
rust = "latest"
claude-code = { version = "latest", minimum_release_age = "0" }
tree-sitter = "latest"
"gem:ruby-lsp" = "latest"
"gem:rubocop" = "latest"
"npm:@olrtg/emmet-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
