brew 'git'
brew 'tmux'
brew 'neovim'
brew 'fzf'
brew 'the_silver_searcher'
brew 'watch'
brew 'starship'

tap 'homebrew/cask-fonts'
cask 'font-jetbrains-mono-nerd-font'

cask 'iterm2'
brew 'rbenv'
brew 'ruby-build'
brew 'postgresql@14'
brew 'libpq'
