" set encoding
set encoding=utf-8

" ______ PLUGINS ______
" disable filetype detection before running Vundle
filetype off
" include Vundle bundle in reatlime path
set rtp+=~/.vim/bundle/Vundle.vim
" begin Vundle operations
call vundle#begin()
" allow Vundle to manage Vundle
Plugin 'VundleVim/Vundle.vim'
" load plugins
source ~/.dotfiles/vim/plugins.vim
" finish Vundle operations
call vundle#end()
" enable filetype detection after running Vundle to allow new types to be picked up
filetype plugin indent on
" _____________________

" unless syntax highlighting is already enabled…
if !exists('g:syntax_on')
  " enable syntax highlighting
  syntax enable
endif
" if ag is available on the system…
if executable('ag')
  " configure Ack to use ag
  let g:ackprg = 'ag --vimgrep'
endif


" enable 24-bit colour
set termguicolors

" set colour scheme
let ayucolor="mirage"
colorscheme ayu

" follows indent of previous line when creating a new line
set autoindent
" follows language-specific indenting rules when creating a new line
set smartindent
" configures folding
set foldmethod=syntax foldlevelstart=30
" configures tabs
set tabstop=2 shiftwidth=2 expandtab
" highlight line containing cursor
set cursorline
" split below and right
set splitbelow splitright
" make searching case insensitive unless the query has capital letters
set ignorecase smartcase
" use 'g' flag by default with :s/foo/bar/
set gdefault
" use 'magic' patterns (extended regular expressions)
set magic
" highlight 100th column
set colorcolumn=96
" I don't like wrapping
set nowrap
" let the statusline handle modes
set noshowmode
" defines tab and trailing space indicators
set listchars=tab:>-,trail:-
" displays hidden characters such as spaces and tabs
set list
" show line numbers
set number
" highlight the results of the last search
set hlsearch
" disable saving of swapfiles
set noswapfile

" load keybindings
source ~/.dotfiles/vim/keybindings.vim
