#!/bin/bash

options=(
    style=round
    width=2.0
    hidpi=on
    order=above
    # active_color=0xff15bdec
    active_color=0xff585b70
    inactive_color=0x00000000
    blacklist="Photomator"
)

borders "${options[@]}"
