require('core.config.theme')
require('core.config.lualine')
require('core.config.nvim-tree')
require('core.config.telescope')
require('core.config.nvim-treesitter')
require('core.config.undotree')
require('core.config.whitespace')
require('core.config.nvim-autopairs')
require('core.config.gitsigns')
-- require('core.config.completion') -- disabled to play with copilot
require('core.config.lsp')
