require('core.config.theme')
require('core.config.lualine')
require('core.config.nvim-tree')
require('core.config.telescope')
require('core.config.treesitter')
require('core.config.undotree')
require('core.config.whitespace')
require('core.config.nvim-autopairs')
