# set vi movement keys
bindkey -v

# set editor to vim
export EDITOR=nvim
export VISUAL=nvim

# initialise starship prompt
eval "$(starship init zsh)"

# set up command history
# much taken from https://www.soberkoder.com/better-zsh-history/
export HISTSIZE=1000000000 # total loaded in session
export SAVEHIST=1000000000 # total saved
export HISTFILE=~/.zsh_history # where to store history
setopt INC_APPEND_HISTORY # immediately append history to file
export HISTTIMEFORMAT="[%F %T] " # sets the time format
setopt EXTENDED_HISTORY # and allows the time to be recorded

# use most for paging, to enable colour man pages
# as per https://www.howtogeek.com/683134/how-to-display-man-pages-in-color-on-linux/
export PAGER=most

# set up completions in general
autoload -U compinit
compinit

# configure chruby to be available and auto-detecting
source $(brew --prefix)/opt/chruby/share/chruby/chruby.sh
source $(brew --prefix)/opt/chruby/share/chruby/auto.sh

# set up some useful aliases
source ~/.dotfiles/zsh/aliases.sh

# configure fzf
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -l'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
